name: learning
on:
  push:
   branches:
    - main

jobs:
 produce:
  runs-on: ubuntu-24.04

  outputs:
   name: ${{steps.step1.outputs.name}}
  
  steps:
   - name: first-step
     id: step1
     run: |
         name=abhishek;
         echo "name=$name" >> "$GITHUB_OUTPUT"
         echo "name=$name" >> "$GITHUB_ENV"

   - name: second-step
      
     run: |
          echo "name=$name"
          echo "name=${{steps.step1.outputs.name}}"

  consume:
   runs-on: ubuntu-24.04

   needs: produce
   steps:
    - name: consume-step
      run: |
           echo "${{needs.produce.outputs.name}}"